### PR TITLE
update for meteor-1.4 branch of wekan

### PR DESCRIPTION
**Pull request by stephenmoloney**

### CODE REVIEW

**Comment by stephenmoloney** [comment]
@xet7

**Comment by xet7** [comment]
@stephenmoloney 

Wrong branch. Use meteor-1.4 branch.

**Comment by weaktyper** [comment]
@xet7 what do you mean?
Can you elaborate...

**Comment by weaktyper** [comment]
```
GIT_REPO=https://github.com/wekan/wekan.git
+GIT_BRANCH=devel
+USE_RELEASE=false
+GIT_RELEASE=v0.18
```

If you are referring to the above  which is not clean from what you wrote, then I would disagree.

On my machine `.env` GIT_BRANCH is set to `meteor-1.4`.

`env-defaults` are just defaults - those are not meant to be opinionated - so setting it to the `devel` branch is the right thing to do. 

Changing the `env-defaults` to branches for development, etc wouldn't be right to be honest -that is up to the user to decide. 

I could add something to the `README` though advising people to change branches.... 

How does that sound?

**Comment by stephenmoloney** [comment]
@xet7 what do you mean?
Can you elaborate...

I think you could have waited for a discussion before closing the pull request.

```
GIT_REPO=https://github.com/wekan/wekan.git
+GIT_BRANCH=devel
+USE_RELEASE=false
+GIT_RELEASE=v0.18
```

If you are referring to the above  which is not clear from what you wrote, then I would disagree.

On my machine `.env` GIT_BRANCH is set to `meteor-1.4`.

`env-defaults` are just defaults - those are not meant to be opinionated - so setting it to the `devel` or `master` probably more so branch is the right thing to do. (in my opinion) 

I could add something to the `README` though advising people to change branches.... 

How does that sound?

**Pull request merged**
